language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: mlgjOWXkgm/I1eQ9Cy+36BBW1VzPGlogNimt2kAqIfZ/kPBdWciKcNvimQkWaauaZIQy0RufgFp/0fUEhecknFPd73fdUd0ntzs+PcBHZV5oK//ta0tTyAL+hM/uWQWXFhb4spPhuugCIcuCnbIdpXeeewhPgBiSkXa9dqVXwiQ7OUfXj2mAQoZuIP7gG5y86cf/9LeP8+y2Si26UoDg5BnVMWjMbp+7ec/+1A/kh3LFf2ecSu1SSFQSlCgmXzJIXcRjqZWdNWxPqkZQGThxaD838BYaa4SjfEetdvPRPf64s780y88T1Ex2q81XvDkOdp8WUbTB0m4sDBSN5/PsT4346wyEzbU58ajYLvjxPup7TobcUUOEW67DqLrPMEFtW7scN+ku8V49B33F4inQXS91/Nb6mkG9CkWASlxdN23eDsYuCPjCADdTD+6HR4VpIw0oTrzm7Cq8v3R7iTlMoUEHwzkr4d2NVHHvssEYTxrR2xnK0NxtOrRLCQjk62bUCx8lt/T4kVwKaeGGdMcP1YAZ/NfCgJznATO7kbdmsovO58bWU27F9erToYhrJbqXErbzaybb8klcehKsuLmNK3fAIzeCTHghwGhYsuiQizNYiapA5dcBwJCo6NDU4mDMvE6hXXPS4k6oHjYDt9x9hkO0ib/n421+Ad5GPBvomcw=
  app: peaceful-plains-99948
  on:
    repo: mcbanks76/playerWatch
